import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Roboto } from 'next/font/google';

const roboto = Roboto({
  weight: ['100','300','400','500','700','900'],
  style: ['normal','italic'],
  subsets: ['latin'],
});

export const metadata = {
  title: "ONE STOP SHOP",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (

    <ClerkProvider>
      <html lang="en">
        <body
          className={`${roboto.className} antialiased`}
        >
          <link rel="icon" href="/onestopshop.png" sizes="any" />
            {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
